import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Footer from "./(components)/Footer/Footer";
import NavBar from "./(components)/NavBar/NavBar";
import { SessionProviders } from "./providers";
import { CartPageContextProvider } from "./(context)/CartIconContext";
import Cart from "./(components)/Cart/Cart";
import { AlertContextProvider } from "./(context)/AlertContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <SessionProviders>
          <AlertContextProvider>
            <CartPageContextProvider>
              <NavBar/>
                <Cart/>
                  {children}
                <Footer/>
            </CartPageContextProvider>
          </AlertContextProvider>
        </SessionProviders>
      </body>
    </html>
  );
}
